# Generated by Django 4.2.11 on 2026-06-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('technician', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('classification', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('grade', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('maker', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('is_manual', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('coded', 'Coded'), ('noncode', 'Non-Code')], default='coded', max_length=10)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('alternate_codes', models.CharField(blank=True, max_length=200)),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='chips/')),
                ('image_hash', models.CharField(blank=True, max_length=64)),
                ('image_path', models.CharField(blank=True, db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('tech', 'Tech')], default='tech', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('grade', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('maker', models.CharField(max_length=50)),
                ('price_coded', models.IntegerField()),
                ('price_noncode', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
                ('status', models.CharField(default='coded', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('scan_status', models.CharField(default='UNKNOWN', max_length=20)),
                ('matched_chip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.chip')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('price_coded', models.IntegerField(default=0)),
                ('price_noncode', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('tech', 'Tech')], default='tech', max_length=10)),
            ],
            options={
                'unique_together': {('grade', 'role')},
            },
        ),
        migrations.CreateModel(
            name='NonCodePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('tech', 'Tech')], default='tech', max_length=10)),
            ],
            options={
                'unique_together': {('size', 'role')},
            },
        ),
    ]
