# Generated by Django 4.2.11 on 2026-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
